In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/lib/python3/dist-packages/numpy/__init__.py'>

# Creating Arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,7,12])

In [8]:
print(a)

[ 1  2  3  4  5  7 12]


In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [20]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dementional Arrays

In [23]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
n[0, 1]

2

In [30]:
n[0]

array([1, 2, 3])

In [31]:
n[2] = [10, 11, 12]
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [33]:
n[:, 1]

array([ 2,  5, 11])

In [35]:
n[:, 2] = [9, 8, 7]
n

array([[ 1,  2,  9],
       [ 4,  5,  8],
       [10, 11,  7]])

# Random Generated Arrays

In [1]:
np.random.seed(2)
100 * np.random.rand(5, 2)

NameError: name 'np' is not defined

In [41]:
np.random.seed(2)
np.random.randn(5, 2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [44]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [48]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [62]:
b = (10 + (a * 3))
b

array([10, 13, 16, 19, 22])

In [63]:
a * 4

array([ 0,  4,  8, 12, 16])

In [65]:
a > b

array([False, False, False, False, False])

In [67]:
a[a <= b]

array([0, 1, 2, 3, 4])

In [ ]:
a.std()

In [7]:
lin = np.linspace(1, 10, 20)

In [7]:
lin

NameError: name 'lin' is not defined

In [ ]:
import numpy as np
my_array = np.arange(8)
print(my_array)
print(type(my_array))
my_array = np.arange(1,8)
print(my_array)
my_array = np.arange(1,8, 2)
print(my_array)
my_array = np.arange(-1, 9.25, 0.5)
print(my_array)
from_list = np.array([1,2,3], dtype=np.int8)
print(from_list)
print(type(from_list[0]))
### 2D Arrays
from_list = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
print(from_list)
array_2d = np.array((np.arange(0,8,2), np.arange(1,8,2)))
print("1D shape:", my_array.shape)
print("2D shape:", array_2d.shape)
array_2d = array_2d.reshape((4, 2))
print(array_2d)
## Empty Array
empty_array = np.zeros((2, 2))
print(empty_array)
eye_array = np.eye(3, k=1)
eye_array[2,] = [1,2,3]
print(eye_array)
sorted_array = np.sort(eye_array)
print(sorted_array, "\n")
my_list = ["e", "a", "d", "g", "b", "e"]

for i in my_list:
    print(i)